# Generated by Django 5.2.8 on 2026-02-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeevent',
            name='event_type',
            field=models.CharField(default='legacy_event', max_length=100),
            preserve_default=False,
        ),
    ]
