# Generated by Django 5.2.8 on 2026-02-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_type_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='pickup_location',
        ),
    ]
