# Generated by Django 5.2.8 on 2026-02-11 18:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_shippingaddress_pickup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
