# Generated by Django 5.2.8 on 2026-02-15 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_public_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'Shipping Address', 'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_items',
        ),
        migrations.AlterModelTable(
            name='shippingaddress',
            table='shipping_addresses',
        ),
    ]
