# Generated by Django 5.2.8 on 2026-02-15 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={},
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shippingaddress',
            table=None,
        ),
    ]
